############################################################################################################
## Airtap T-Series Vent Controller 3 Button Revision 1
## This version has been replaced by rev2 and is no longer supported
## This version is only here for historical purposes and support
## Wont be submitted to the ESPHome repository
############################################################################################################

esphome:
  name: my-vent
  friendly_name: My Vent
  min_version: 2024.6.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf #https://developers.esphome.io/blog/2025/06/18/sunsetting-support-for-idf-4x/

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  - platform: esphome
    password: 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "My-Vent Fallback Hotspot"
    password: ""

captive_portal:

i2c:
  id: airtap_i2c
  sda: GPIO6
  scl: GPIO7
  scan: True
  frequency: 400kHz

globals:
  - id: fan_speed
    type: int
    restore_value: yes
    initial_value: '0'
  - id: panel_disabled
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: display_enabled
    type: bool
    restore_value: yes
    initial_value: 'true'

switch:
  - platform: template
    name: "Disable Panel Buttons"
    id: panel_disable_switch
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:lock
    lambda: |-
      return id(panel_disabled);
    turn_on_action:
      - lambda: |-
          id(panel_disabled) = true;
          id(panel_disable_switch).publish_state(true);
    turn_off_action:
      - lambda: |-
          id(panel_disabled) = false;
          id(panel_disable_switch).publish_state(false);
  - platform: template
    name: "Display"
    id: display_switch
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:monitor
    lambda: |-
      return !id(display_enabled);
    turn_on_action:
      - lambda: |-
          id(display_enabled) = false;
          id(display_switch).publish_state(true);
    turn_off_action:
      - lambda: |-
          id(display_enabled) = true;
          id(display_switch).publish_state(false);

button:
  - platform: restart
    id: restart_button
    icon: mdi:power-cycle
    name: "ESP Reboot"

number:
  - platform: template
    name: "Fan Speed"
    id: fan_speed_number
    min_value: 0
    max_value: 10
    step: 1
    restore_value: true
    set_action:
      - lambda: |-
          id(fan_speed) = (int)(x);
          id(fan_speed_number).publish_state(x);

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    calibration:      
      #Inversed for PTC
      - 3.389kOhm -> 0°C
      - 10.0kOhm -> 25°C
      - 27.219kOhm -> 50°C
    name: "AC Infinity Temperature"
    id: temp_sensor
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    icon: "mdi:thermometer"

  - platform: resistance
    id: temp_resistance_reading
    sensor: adc_sensor
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: adc
    pin: GPIO4
    id: adc_sensor
    attenuation: 12db

output:
  - platform: ledc
    pin: 
      number: GPIO2
      ignore_strapping_warning: true
    id: pwm_output_1
    frequency: 1000 Hz
    # power_supply: fan_speed

  - platform: ledc
    pin: GPIO3
    id: pwm_output_2
    frequency: 1000 Hz
    # power_supply: fan_speed

display:
  - platform: ssd1306_i2c
    id: display_1306
    model: "SSD1306 128x64"
    address: 0x3C
    # Celcius
    # lambda: |-
    #   it.printf(1, 0, id(myfont), "Airtap T-Series");
    #   it.printf(0, 14, id(myfont), "Temp: %.1f°C", id(temp_sensor).state);
    #   it.printf(0, 28, id(myfont), "Fan Speed: %d", id(fan_speed));
    # Fahrenheit
    lambda: |-
      it.printf(1, 0, id(myfont), "Airtap T-Series");
      float temp_f = (id(temp_sensor).state * 9.0 / 5.0) + 32.0;
      it.printf(0, 14, id(myfont), "Temp: %.1f°F", temp_f);
      it.printf(0, 28, id(myfont), "Fan Speed: %d", id(fan_speed));


font:
  - file: "gfonts://Roboto"
    id: myfont
    size: 12

binary_sensor:
  - platform: gpio
    pin: GPIO10
    name: "Mode Button"
    id: button_mode
    on_press:
      then:
        - lambda: |-
            if (!id(panel_disabled)) {
              if (id(fan_speed) == 0) {
                id(fan_speed) = 10;
              } else {
                id(fan_speed) = 0;
              }
              id(fan_speed_number).publish_state(id(fan_speed)); // Publish updated state
            }

  - platform: gpio
    pin: 
      number: GPIO8
      ignore_strapping_warning: true
    name: "Up Button"
    id: button_up
    on_press:
      then:
        - lambda: |-
            if (!id(panel_disabled)) {
              if (id(fan_speed) < 10){
                id(fan_speed) += 1;
                id(fan_speed_number).publish_state(id(fan_speed)); // Publish updated state
              }
            }

  - platform: gpio
    pin: 
      number: GPIO9
      ignore_strapping_warning: true
    name: "Down Button"
    id: button_down
    on_press:
      then:
        - lambda: |-
            if (!id(panel_disabled)) {
              if (id(fan_speed) > 0){
                id(fan_speed) -= 1;
                id(fan_speed_number).publish_state(id(fan_speed)); // Publish updated state
              }
            }

light:
  - platform: monochromatic
    output: pwm_output_1
    name: "Fan 1 Speed"
    id: fan_1
    internal: true  # Hide this from Home Assistant

  - platform: monochromatic
    output: pwm_output_2
    name: "Fan 2 Speed"
    id: fan_2
    internal: true  # Hide this from Home Assistant

interval:
  - interval: 1s
    then:
      - light.turn_on:
          id: fan_1
          brightness: !lambda |-
            if (id(fan_speed) == 0) {
              return 0.0;
            } else if (id(fan_speed) == 1) {
              return 0.38;  // Minimum value to start the fan
            } else {
              return (id(fan_speed) + 3) / 13.0;
            }
      - light.turn_on:
          id: fan_2
          brightness: !lambda |-
            if (id(fan_speed) == 0) {
              return 0.0;
            } else if (id(fan_speed) == 1) {
              return 0.38;  // Minimum value to start the fan
            } else {
              return (id(fan_speed) + 3) / 13.0;
            }
